import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#131314",
        surface: "#131314",
        "surface-dim": "#131314",
        "surface-bright": "#39393a",
        "surface-container-lowest": "#0e0e0f",
        "surface-container-low": "#1c1b1c",
        "surface-container": "#201f20",
        "surface-container-high": "#2a2a2b",
        "surface-container-highest": "#353436",
        "surface-variant": "#353436",
        "on-surface": "#e5e2e3",
        "on-surface-variant": "#d1c5b4",
        outline: "#9a8f80",
        "outline-variant": "#4e4639",
        primary: "#e9c176",
        "on-primary": "#412d00",
        "primary-container": "#c5a059",
        "on-primary-container": "#4e3700",
        "primary-fixed": "#ffdea5",
        "primary-fixed-dim": "#e9c176",
        secondary: "#ffb3b5",
        "on-secondary": "#5f131e",
        "secondary-container": "#802c35",
        "on-secondary-container": "#ff9da2",
        "secondary-fixed": "#ffdada",
        "secondary-fixed-dim": "#ffb3b5",
        tertiary: "#ccc6b9",
        "on-tertiary": "#333027",
        "tertiary-container": "#aaa598",
        "on-tertiary-container": "#3e3b31",
        "tertiary-fixed": "#e8e2d4",
        "tertiary-fixed-dim": "#ccc6b9",
        crimson: "#c81e1e",
        "crimson-deep": "#681a24",
      },
      fontFamily: {
        display: ["'EB Garamond'", "Georgia", "serif"],
        headline: ["'EB Garamond'", "Georgia", "serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Syne", "sans-serif"],
      },
      spacing: {
        "gutter-mobile": "1rem",
        "margin-mobile": "1.25rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        margin: "3rem",
      },
      boxShadow: {
        "card-ambient": "0 20px 48px -12px rgba(0, 0, 0, 0.75), 0 0 1px 1px rgba(197, 160, 89, 0.25)",
        "card-gold": "0 10px 30px -5px rgba(197, 160, 89, 0.2)",
        "card-deep": "0 25px 60px -15px rgba(0, 0, 0, 0.95)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
